# -*- coding: utf-8 -*-
"""AIML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEMHbcl1Lnzf9Ii7gK2h9i1qeYwwbhav
"""

from flask import Flask, render_template, request

app = Flask(__name__)

def bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif bmi < 25:
        return "Normal weight"
    elif bmi < 30:
        return "Overweight"
    else:
        return "Obese"

def activity_factor(level):
    factors = {
        "sedentary": 1.2,
        "light": 1.375,
        "moderate": 1.55,
        "active": 1.725
    }
    return factors.get(level, 1.2)

def calculate_bmr(gender, weight, height_cm, age):

    if gender == "male":
        return (10 * weight) + (6.25 * height_cm) - (5 * age) + 5
    else:
        return (10 * weight) + (6.25 * height_cm) - (5 * age) - 161

def calorie_target(goal, tdee):
    if goal == "fat_loss":
        return int(tdee - 400)
    elif goal == "muscle_gain":
        return int(tdee + 300)
    else:
        return int(tdee)

def protein_target(goal, weight):
    if goal == "fat_loss":
        return round(weight * 1.6, 1)
    elif goal == "muscle_gain":
        return round(weight * 1.8, 1)
    else:
        return round(weight * 1.4, 1)

def workout_plan(days, mode, goal):
    home = {
        3: ["Day 1: Full Body Strength", "Day 2: Cardio + Core", "Day 3: Lower Body + HIIT"],
        4: ["Day 1: Upper Body", "Day 2: Lower Body", "Day 3: Cardio + Core", "Day 4: Full Body Strength"],
        5: ["Day 1: Upper Body", "Day 2: Lower Body", "Day 3: Cardio", "Day 4: Core + HIIT", "Day 5: Full Body"],
        6: ["Day 1: Push", "Day 2: Pull", "Day 3: Legs", "Day 4: Cardio", "Day 5: Core", "Day 6: Full Body"]
    }

    gym = {
        3: ["Day 1: Full Body (Gym)", "Day 2: Cardio + Core", "Day 3: Strength Split"],
        4: ["Day 1: Chest + Triceps", "Day 2: Back + Biceps", "Day 3: Legs", "Day 4: Cardio + Abs"],
        5: ["Day 1: Chest", "Day 2: Back", "Day 3: Legs", "Day 4: Shoulders", "Day 5: Arms + Core"],
        6: ["Day 1: Push", "Day 2: Pull", "Day 3: Legs", "Day 4: Push", "Day 5: Pull", "Day 6: Legs"]
    }

    plan = home.get(days, home[3]) if mode == "home" else gym.get(days, gym[3])

    tips = []
    if goal == "fat_loss":
        tips = ["Add 20 minutes walking daily", "Keep rest time short (30–60 sec)", "Drink 2–3L water daily"]
    elif goal == "muscle_gain":
        tips = ["Increase weights gradually", "Eat high-protein meals", "Sleep 7–8 hours for recovery"]
    else:
        tips = ["Stay consistent", "Stretch daily", "Maintain balanced diet"]

    return plan, tips

def diet_plan(pref, budget, goal):
    base = {
        "veg": {
            "low": [
                "Breakfast: Oats/Upma + Banana",
                "Lunch: Rice + Dal + Veg curry + Curd",
                "Snack: Roasted peanuts / Sprouts",
                "Dinner: Chapati + Chana/Paneer + Salad"
            ],
            "medium": [
                "Breakfast: Poha + Milk + Fruit",
                "Lunch: Chapati + Rajma + Salad",
                "Snack: Fruit + Nuts",
                "Dinner: Rice + Sambar + Veg + Curd"
            ],
            "high": [
                "Breakfast: Greek yogurt + Oats + Fruit",
                "Lunch: Quinoa/Roti + Paneer + Salad",
                "Snack: Protein smoothie",
                "Dinner: Millet roti + Mixed veg + Dal"
            ]
        },
        "eggetarian": {
            "low": [
                "Breakfast: 2 Eggs + Toast",
                "Lunch: Rice + Dal + Veg curry",
                "Snack: Boiled egg + Banana",
                "Dinner: Chapati + Egg curry + Salad"
            ],
            "medium": [
                "Breakfast: Omelette + Oats",
                "Lunch: Chapati + Egg curry + Veg",
                "Snack: Fruit + Nuts",
                "Dinner: Rice + Sambar + Egg bhurji"
            ],
            "high": [
                "Breakfast: Egg white omelette + Fruit",
                "Lunch: Brown rice + Eggs + Salad",
                "Snack: Protein shake",
                "Dinner: Chapati + Eggs + Veg soup"
            ]
        },
        "nonveg": {
            "low": [
                "Breakfast: Oats + Banana",
                "Lunch: Rice + Chicken curry + Veg",
                "Snack: Boiled egg / Chana",
                "Dinner: Chapati + Fish/Chicken + Salad"
            ],
            "medium": [
                "Breakfast: Omelette + Milk",
                "Lunch: Chapati + Chicken + Salad",
                "Snack: Fruit + Nuts",
                "Dinner: Rice + Fish curry + Veg"
            ],
            "high": [
                "Breakfast: Smoothie + Eggs",
                "Lunch: Brown rice + Grilled chicken + Salad",
                "Snack: Protein bar/shake",
                "Dinner: Chapati + Fish + Soup"
            ]
        }
    }

    meals = base.get(pref, base["veg"]).get(budget, base["veg"]["low"])

    tips = []
    if goal == "fat_loss":
        tips = ["Avoid sugary drinks", "Prefer grilled/boiled foods", "Increase fiber intake"]
    elif goal == "muscle_gain":
        tips = ["Add one extra protein snack", "Include milk/curd daily", "Add healthy carbs like oats/rice"]
    else:
        tips = ["Eat balanced meals", "Avoid overeating", "Stay hydrated"]

    return meals, tips

@app.route("/", methods=["GET"])
def home():
    return render_template("index.html")

@app.route("/result", methods=["POST"])
def result():
    name = request.form.get("name")
    age = int(request.form.get("age"))
    gender = request.form.get("gender")
    height = float(request.form.get("height"))
    weight = float(request.form.get("weight"))
    goal = request.form.get("goal")
    activity = request.form.get("activity")
    mode = request.form.get("mode")
    days = int(request.form.get("days"))
    pref = request.form.get("pref")
    budget = request.form.get("budget")

    h_m = height / 100
    bmi = round(weight / (h_m ** 2), 2)
    bmi_cat = bmi_category(bmi)

    bmr = calculate_bmr(gender, weight, height, age)
    tdee = bmr * activity_factor(activity)

    cal = calorie_target(goal, tdee)
    protein = protein_target(goal, weight)

    wplan, wtips = workout_plan(days, mode, goal)
    dplan, dtips = diet_plan(pref, budget, goal)

    goal_text = {
        "fat_loss": "Fat Loss",
        "muscle_gain": "Muscle Gain",
        "maintenance": "Maintenance"
    }.get(goal, "Maintenance")

    return render_template(
        "result.html",
        name=name,
        age=age,
        gender=gender.title(),
        bmi=bmi,
        bmi_cat=bmi_cat,
        bmr=int(bmr),
        tdee=int(tdee),
        cal_target=cal,
        prot_target=protein,
        goal_text=goal_text,
        mode=mode.title(),
        days=days,
        workout=wplan,
        wtips=wtips,
        diet=dplan,
        dtips=dtips
    )

if __name__ == "__main__":
    app.run(debug=True)